site_name: OOPAO Documentation
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - Light Path: light_path.md
  - Atmosphere: atmosphere.md
  - Source: source.md
  - Extended Source: extended_source.md
  - Telescope: telescope.md
  - Deformable Mirror: deformable_mirror.md
  - SHWFS: shwfs.md
  - Correlating SHWFS: correlating_shwfs.md
  - NCPA: ncpa.md
  - Detector: detector.md
  - Interaction Matrix: interaction_matrix.md
  - Sharepoint: sharepoint.md
  - Layer: layer.md
  - Misregistration: misregistration.md
